/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ad5a74eb-e019-4f5c-a663-ae384a30afea",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_7Pbn6KeZ0",
    "aws_user_pools_web_client_id": "79olqp5j7cn0cju5v9kr0k415f",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://qd6t7gdovvbqnapr2gdebn42ze.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
